# Generated by Django 3.2.18 on 2023-08-16 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=100)),
                ('rate', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('phone_number', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=100)),
                ('qualification', models.CharField(default='', max_length=100)),
                ('dob', models.CharField(default='', max_length=100)),
                ('place', models.CharField(default='', max_length=100)),
                ('post', models.CharField(default='', max_length=100)),
                ('pin', models.CharField(default='', max_length=100)),
                ('district', models.CharField(default='', max_length=100)),
                ('email_id', models.CharField(default='', max_length=100)),
                ('photo', models.CharField(default='', max_length=100)),
                ('id_proof', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('LOGIN', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='recycle_unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(default='', max_length=100)),
                ('place', models.CharField(default='', max_length=100)),
                ('post', models.CharField(default='', max_length=100)),
                ('pin', models.CharField(default='', max_length=100)),
                ('district', models.CharField(default='', max_length=100)),
                ('phone_number', models.CharField(default='', max_length=100)),
                ('email_id', models.CharField(default='', max_length=100)),
                ('LOGIN', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
    ]
