# Generated by Django 3.2.18 on 2023-08-16 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=100)),
                ('notification', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('phone_number', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('place', models.CharField(default='', max_length=100)),
                ('post', models.CharField(default='', max_length=100)),
                ('pin', models.CharField(default='', max_length=100)),
                ('district', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=100)),
                ('feedback', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('USER_ID', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=100)),
                ('complaint', models.CharField(default='', max_length=100)),
                ('reply', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('USER_ID', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('WORKER_ID', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
    ]
