# Generated by Django 3.2.18 on 2023-08-16 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_allocation_category_complaint_feedback_notifications_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='WORKER_ID',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='myapp.worker'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='USER_ID',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='USER_ID',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=100)),
                ('request', models.CharField(default='', max_length=100)),
                ('USER_ID', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=100)),
                ('amount', models.CharField(default='', max_length=100)),
                ('RECYCLE_UNIT_ID', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='myapp.recycle_unit')),
            ],
        ),
        migrations.CreateModel(
            name='pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('phone_number', models.CharField(default='', max_length=100)),
                ('id_proof', models.CharField(default='', max_length=100)),
                ('qualification', models.CharField(default='', max_length=100)),
                ('experiance', models.CharField(default='', max_length=100)),
                ('LOGIN', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=100)),
                ('PRODUCT_ID', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('USER_ID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
