# Generated by Django 3.2.18 on 2023-08-16 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20230816_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocation',
            old_name='WORKER_ID',
            new_name='WORKER',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='PRODUCT_ID',
            new_name='PRODUCT',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='USER_ID',
            new_name='USER',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='USER_ID',
            new_name='USER',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='USER_ID',
            new_name='USER',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='RECYCLE_UNIT_ID',
            new_name='RECYCLE_UNIT',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='USER_ID',
            new_name='USER',
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=100)),
                ('amount', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('USER_ID', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
