# Generated by Django 3.2.18 on 2023-08-16 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20230816_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='USER_ID',
            new_name='USER',
        ),
        migrations.CreateModel(
            name='order_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.CharField(default='', max_length=100)),
                ('PRODUCT', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('USER', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
