# Generated by Django 3.2.18 on 2023-08-16 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20230816_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ORDERMAIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.order_main'),
        ),
    ]
