# Generated by Django 4.2.4 on 2023-08-24 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_request_waste_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='LOGIN',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
    ]
