# Generated by Django 4.2.4 on 2023-08-24 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_user_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='WORKER',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='myapp.worker'),
        ),
    ]
