# Generated by Django 4.2.4 on 2023-09-26 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_category_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
